### ISSUE TITLE
Failed to meet dependencies on build

### ISSUE THREAD

**Issue by mattplindsay** [annot8/annot8-components#55]
Hi All,
Using a fresh clone based on Master on commit [af57112](https://github.com/annot8/annot8-components/commit/af57112a10ee52b13ca614b6c204ea78bb04a636) I cloned to a folder on my Ubuntu 20.0
4LTS.
Runing `mvn clean install`
Gives
`Failed to execute goal on project annot8-components: Could not resolve dependencies for project io.annot8:annot8-components:pom:1.3.0-SNAPSHOT: Failure to find io.annot8:annot8-api:jar:1.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of oss-sonatype has elapsed or updates are forced `

Does anyone have any clues why this might be or are the able to replicate?

**Comment by jamesdbaker** [comment]
Ah, we've pushed some new versions of the API recently and it looks like the components weren't updated. Once the new versions of the API and implementation have made it on to Maven Central I'll do a new commit of the components with the updated versions.

In the mean time, you can build and install the other libraries locally and then update the versions in `pom.xml`

**Comment by stuarthendren** [comment]
If you just change 1.2-snapshot to 1.2 that should fix it for now. I'll publish new versions tomorrow.

**Comment by mattplindsay** [comment]
Thanks @stuarthendren . I gave that a go and changed line 72 of [the master POM](https://github.com/annot8/annot8-components/blob/master/pom.xml) to 1.2 but unfortunately that didn't work. I'll pull again once you publish.. Thanks for the response.

**Comment by stuarthendren** [comment]
@mattplindsay This issue should be fixed now. Re-open if not.

Just FYI, we've changes the branching structure.

- `main` - used for releases only 
- `develop` - used for the development and works with SNAPSHOT releases.

So for general development you should start a new branch from `develop` and make PRs to `develop`.
To make this easier in github the `develop` is set to the main github branch.
